### ISSUE TITLE
AngularJS 1.3.15

### ISSUE THREAD

**Issue by nunos7** [sdorra/angular-dashboard-framework#101]
Hi Sebastian,
I updated the version of angular to 1.3.15, and the editable attribute doesn't work, i think the problem is because the attribute is passed as string, and the ngIf evaluate always true.

You have any suggestion to put this right?

NS

**Comment by ebtc** [comment]
We also experience some issues since updating to 0.8 of ADF (also using Angular 1.3.15). Our issue sounds much like issue #60: you can move widgets within a column, but not to another. When moving a widget outside the containing column there is also no dropzone hint (as it used to be). Maybe an issue with sortable (i have tried both 1.1.1 and 1.2.0 - same result).

**Comment by sdorra** [comment]
@ebtc please open a new ticket for the move problem.
