### ISSUE TITLE
help modifying the dashboard

### ISSUE THREAD

**Issue by gerardp** [sdorra/angular-dashboard-framework#113]
Hi, i want to change the behavior of the maximize function: hide all the widgets except the one's that are maximizing, similar to this:
http://www.drupal.geek.nz/static/dashboard/demo.html

any suggestions? i don't know where to start.

**Comment by eppak** [comment]
Hi, i think you have to work with the source (instead of the minified). When you click maximize button there is a $scope.openFullScreen defined in widget.js; there you can access to dashboard.widgets list and, for each widget except the current, you can change a property to hide the widget. This property is another thing you have to add to the widget $scope (in widget.js) and then add a ng-show variable to the widget.html template.

Hope this help as a start.

**Comment by gerardp** [comment]
Hi @eppak, thanks for the info.
The dashboard now can hide the others widgets, but now, the doubt that i have is how can i force, to the visible widget, occupy all the screen.

**Comment by eppak** [comment]
The adf use $modal service to manage the overlay that is part of the bootstrap JS libs (handled by https://angular-ui.github.io/bootstrap/). I think that you can use windowClass options to add a custom class and make it bigger with CSS.

Hope that help you.
